```{r}
data(CPS85 , package = "mosaicData")
View(CPS85)
```


```{r}
# In building a ggplot2 graph, only the first two functions described below are required. The other functions are optional and can appear in any order.
 
## first function in building a graph is the ggplot function. 

# It specifies the:
# Data frame containing the data to be plotted
# The mapping of the variables to visual properties of the graph.
# The mappings are placed within the aes function (where aes stands for aesthetics).
```


```{r}
############ specify dataset and mapping ############
library(ggplot2)

ggplot(data = CPS85,mapping = aes(x = exper, y = wage))
#Why is the graph empty? 
#We specified that the exper variable should be mapped to the x-axis and that the wage should be mapped to the y-axis, but we haven’t yet specified what we wanted placed on the graph.
```


```{r}
# Geoms are the geometric objects (points, lines, bars, etc.) that can be placed on a graph. They are added using functions that start with geom_
```
```{r}
ggplot(data = CPS85,mapping = aes(x = exper, y = wage))+geom_point()
```
```{r}
# Removing Outlier

library(dplyr)
plotdata <- filter(CPS85 ,wage < 40)

ggplot(data = plotdata, mapping =aes(x= exper,y= wage))+geom_point()
```
```{r}
# let’s add a line of best fit. We can do this with the geom_smooth function. Options control the type of line (linear, quadratic, nonparametric), the thickness of the line, the line’s color, and the presence or absence of a confidence interval. Here we request a linear regression (method = lm) line (where lm stands for linear model).
```

```{r}
ggplot(data = plotdata,
mapping = aes(x = exper, y = wage)) +
geom_point(color = "cornflowerblue",
alpha = .7,
size = 3) +
geom_smooth(method = "lm")

#(se = FALSE) was added to suppresses the confidence intervals.
ggplot(data = plotdata,
mapping = aes(x = exper, y = wage)) +
geom_point(color = "cornflowerblue",
alpha = .7,
size = 3) +
geom_smooth(method = "lm",se=FALSE)

```

```{r}
###### Facets reproduce a graph for each level a given variable (or combination of variables).####
ggplot(data = plotdata,mapping = aes(x = exper,y = wage,color = sex)) +
geom_point(alpha = .7) +
geom_smooth(method = "lm",se = FALSE) +
scale_x_continuous(breaks = seq(0, 60, 10)) +
scale_y_continuous(breaks = seq(0, 30, 5),label = scales::dollar) +
scale_color_manual(values = c("indianred3","cornflowerblue")) +facet_wrap(~sector)
#In the above we have color = sex but Here in scale_color_manual we are telling the PC not to take default values instead take the one satisfied in c()

# facet_wrap(~sector)--> This is making different graphs according to sector
```
```{r}
ggplot(data = plotdata,mapping = aes(x = exper,y = wage,color = sex)) +
geom_point(alpha = .7,size = 3) +
geom_smooth(method = "lm",se = FALSE,size = 1.5)
```
```{r}
ggplot(data = plotdata,mapping = aes(x = exper,y = wage,color = sex)) +
geom_point(alpha = .7) +
geom_smooth(method = "lm",se = FALSE) +
scale_x_continuous(breaks = seq(0, 60, 10)) +
scale_y_continuous(breaks = seq(0, 30, 5),label = scales::dollar) +
scale_color_manual(values = c("indianred3","cornflowerblue")) +
facet_wrap(~sector) +

  labs(title = "Relationship between wages and experience",
     subtitle = "Current Population Survey",
     caption= "source: http://mosaic-web.org/",
     x = " Years of Experience",
     y = "Hourly Wage",
     color = "Gender")
```

```{r}
ggplot(Marriage,
aes(x = race,
y = ..count.. / sum(..count..))) +
geom_bar() +
labs(x = "Race",
y = "Percent",
title = "Participants by race") +
scale_y_continuous(labels = scales::percent)
```

